-- MySQL Script generated by MySQL Workbench
-- 05/05/17 22:02:30
-- Model: New Model    Version: 1.0

-- -----------------------------------------------------
-- DATABASE mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rainhadasucata
-- -----------------------------------------------------
--CREATE DATABASE IF NOT EXISTS `rainhadasucata` DEFAULT CHARACTER SET latin1 ;
USE `rainhadasucata` ;

-- -----------------------------------------------------
-- Table `rainhadasucata`.`ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`ci_sessions` (
  `id_session` VARCHAR(40) NOT NULL DEFAULT '0',
  `ip_address` VARCHAR(45) NOT NULL DEFAULT '0',
  `user_agent` VARCHAR(120) NOT NULL,
  `last_activity` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `user_data` TEXT NOT NULL,
  PRIMARY KEY (`id_session`),
  INDEX `last_activity_idx` (`last_activity` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`clientes` (
  `id_clientes` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_clientes` VARCHAR(50) NOT NULL,
  `sobrenome_clientes` VARCHAR(70) NOT NULL,
  `cpf_cnpj_clientes` VARCHAR(20) NOT NULL,
  `sexo_clientes` CHAR NOT NULL,
  `telefone_clientes` VARCHAR(20) NOT NULL,
  `celular_clientes` VARCHAR(20) NULL,
  `email_clientes` VARCHAR(100) NULL,
  `cep_clientes` VARCHAR(20) NOT NULL,
  `logradouro_clientes` VARCHAR(70) NOT NULL,
  `numero_clientes` VARCHAR(15) NULL,
  `bairro_clientes` VARCHAR(50) NOT NULL,
  `cidade_clientes` VARCHAR(50) NOT NULL,
  `estado_clientes` VARCHAR(2) NOT NULL,
  `complemento_clientes` VARCHAR(255) NULL,
  `data_cadastro_clientes` TIMESTAMP NOT NULL,
  `deletado_clientes` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_clientes`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`id_clientes` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`produtos` (
  `id_produtos` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(80) NOT NULL,
  `marca_produto` VARCHAR(45) NULL,
  `descricao_produto` TEXT NULL,
  `preco_compra_produto` DECIMAL(10,2) NULL,
  `preco_venda_produto` DECIMAL(10,2) NOT NULL,
  `margem_venda_produto` DECIMAL(10,2) NULL,
  `estoque_produto` INT(11) NOT NULL,
  `estoque_minimo_produto` INT(11) NULL,
  `status_produto` TINYINT(1) NOT NULL DEFAULT 1,
  `deletado_produto` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_produtos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`permissoes` (
  `id_permissoes` INT NOT NULL AUTO_INCREMENT,
  `nome_permissoes` VARCHAR(80) NOT NULL,
  `permissoes` TEXT NOT NULL,
  `data_criacao_permissoes` TIMESTAMP NOT NULL,
  `situacao_permissoes` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_permissoes`),
  UNIQUE INDEX `id_permissoes_UNIQUE` (`id_permissoes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`lojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`lojas` (
  `id_lojas` INT NOT NULL AUTO_INCREMENT,
  `nome_lojas` VARCHAR(100) NOT NULL,
  `tipo_lojas` INT NOT NULL,
  `cep_lojas` VARCHAR(15) NOT NULL,
  `logradouro_lojas` VARCHAR(70) NOT NULL,
  `numero_lojas` VARCHAR(20) NULL,
  `bairro_lojas` VARCHAR(50) NOT NULL,
  `cidade_lojas` VARCHAR(50) NOT NULL,
  `estado_lojas` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_lojas`),
  UNIQUE INDEX `id_lojas_UNIQUE` (`id_lojas` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`usuarios` (
  `id_usuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_usuarios` VARCHAR(50) NOT NULL,
  `sobrenome_usuarios` VARCHAR(70) NOT NULL,
  `cpf_usuarios` VARCHAR(20) NOT NULL,
  `data_nascimento_usuarios` DATE NOT NULL,
  `sexo_usuarios` CHAR NOT NULL,
  `telefone_usuarios` VARCHAR(20) NOT NULL,
  `celular_usuarios` VARCHAR(20) NULL,
  `email_usuarios` VARCHAR(80) NOT NULL,
  `nome_login_usuarios` VARCHAR(50) NOT NULL,
  `senha_usuarios` VARCHAR(45) NOT NULL,
  `imagem_usuarios` VARCHAR(255) NULL,
  `nivel_usuarios` INT(11) NOT NULL,
  `status_usuarios` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro_usuarios` TIMESTAMP NOT NULL,
  `deletado_usuarios` TINYINT(1) NOT NULL DEFAULT 0,
  `fk_id_permissao` INT NOT NULL,
  `fk_id_loja` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  INDEX `fk_usuarios_permissoes1_idx` (`fk_id_permissao` ASC),
  INDEX `fk_usuarios_Lojas1_idx` (`fk_id_loja` ASC),
  UNIQUE INDEX `nomeUsuario_UNIQUE` (`nome_login_usuarios` ASC),
  UNIQUE INDEX `id_usuarios_UNIQUE` (`id_usuarios` ASC),
  CONSTRAINT `fk_usuarios_permissoes1`
    FOREIGN KEY (`fk_id_permissao`)
    REFERENCES `rainhadasucata`.`permissoes` (`id_permissoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_Lojas1`
    FOREIGN KEY (`fk_id_loja`)
    REFERENCES `rainhadasucata`.`lojas` (`id_lojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`vendas` (
  `id_vendas` INT NOT NULL AUTO_INCREMENT,
  `metodo_pagamento` VARCHAR(20) NOT NULL,
  `valor_total` VARCHAR(45) NOT NULL,
  `data_hora_vendas` TIMESTAMP NOT NULL,
  `desconto_vendas` VARCHAR(45) NULL,
  `fk_id_cliente` INT(11) NOT NULL,
  `fk_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_vendas`),
  INDEX `fk_vendas_clientes1` (`fk_id_cliente` ASC),
  INDEX `fk_vendas_usuarios1` (`fk_id_usuario` ASC),
  UNIQUE INDEX `id_vendas_UNIQUE` (`id_vendas` ASC),
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`fk_id_cliente`)
    REFERENCES `rainhadasucata`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `rainhadasucata`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`itens_de_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`itens_de_vendas` (
  `id_idv` INT NOT NULL AUTO_INCREMENT,
  `quantidade_idv` INT(11) NULL,
  `fk_id_venda` INT NOT NULL,
  `fk_id_produto` INT(11) NOT NULL,
  PRIMARY KEY (`id_idv`),
  INDEX `fk_itens_de_vendas_vendas1` (`fk_id_venda` ASC),
  INDEX `fk_itens_de_vendas_produtos1` (`fk_id_produto` ASC),
  CONSTRAINT `fk_itens_de_vendas_vendas1`
    FOREIGN KEY (`fk_id_venda`)
    REFERENCES `rainhadasucata`.`vendas` (`id_vendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_de_vendas_produtos1`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `rainhadasucata`.`produtos` (`id_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`produto_tem_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`produto_tem_usuario` (
  `data_hora_ptu` TIMESTAMP NOT NULL,
  `fk_id_produto` INT(11) NOT NULL,
  `fk_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`data_hora_ptu`, `fk_id_produto`, `fk_id_usuario`),
  INDEX `fk_produtos_has_usuarios_usuarios1_idx` (`fk_id_usuario` ASC),
  INDEX `fk_produtos_has_usuarios_produtos1_idx` (`fk_id_produto` ASC),
  CONSTRAINT `fk_produtos_has_usuarios_produtos1`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `rainhadasucata`.`produtos` (`id_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_usuarios_usuarios1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `rainhadasucata`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rainhadasucata`.`cliente_tem_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rainhadasucata`.`cliente_tem_usuario` (
  `data_hora_ctu` TIMESTAMP NOT NULL,
  `fk_id_clientes` INT(11) NOT NULL,
  `fk_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`data_hora_ctu`, `fk_id_clientes`, `fk_id_usuario`),
  INDEX `fk_clientes_has_usuarios_usuarios1_idx` (`fk_id_usuario` ASC),
  INDEX `fk_clientes_has_usuarios_clientes1_idx` (`fk_id_clientes` ASC),
  CONSTRAINT `fk_clientes_has_usuarios_clientes1`
    FOREIGN KEY (`fk_id_clientes`)
    REFERENCES `rainhadasucata`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_usuarios_usuarios1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `rainhadasucata`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;